### ISSUE TITLE
안부 추가 화면에서 문제

### ISSUE THREAD

**Issue by moungJae** [Relief-Post-Office/Relief-Post-Office#13]
### 최초 저장 버튼 클릭시
<img src="https://user-images.githubusercontent.com/81675254/186489315-04c7889d-53b1-436e-86fb-1abe43e53b14.jpg" width="200" height="400">

### 클릭 후 다시 저장 버튼 클릭시 (미반응)
<img src="https://user-images.githubusercontent.com/81675254/186489362-5cb81697-f755-4fc0-868d-977c898a1a8f.jpg" width="200" height="400">

### 버그 내용

안부 추가 화면에서 저장 버튼의 listener 가 정상적으로 동작되지 않는 문제를 발견했습니다.
안부 추가 파트를 맡으셨던 Jeensh 님이 저 부분을 수정해주셨으면 합니다.
저도 리스너가 왜 동작되지 않는지 코드를 살펴보도록 하겠습니다.

**Comment by moungJae** [comment]
수정했습니다.

![image](https://user-images.githubusercontent.com/81675254/186493364-cd6e603b-82b7-49e4-8adc-da4fba3fd86f.png)

safety 패키지의 AddWardSafetyActivity 클래스에 setSaveButton 메서드 부분입니다.
시간 설정을 안했거나 질문 설정을 하지 않은 경우 버튼이 다시 클릭이 가능하도록 설정을 해주셔야 합니다.
리팩토링 하실 때 "it.isClickable = true" 를 추가해주시고 it 를 다른 이름으로 변경해주세요.

**Comment by Jeensh** [comment]
말씀해주신 내용 참고하여 수정하였습니다!! bb
- 같은 이유로 EditWardSafetyActivity(질문 수정)에서도 질문을 모두 선택 취소 후 저장버튼 누를 시
다시 저장버튼을 누를 수 없는 경우도 수정하였습니다
