### ISSUE TITLE
피보호자의 안부를 삭제할 권한

### ISSUE THREAD

**Issue by moonheee** [Relief-Post-Office/Relief-Post-Office#5]
피보호자의 안부를 삭제할 때 어떤 사람만 삭제할 수 있을까요?

======현재 데이터베이스======
Document 명 : 안부 id
- 질문 목록
- 몇 분 후 강제 알람할 지(피보호자)
- 요일(피보호자)
- 시간(피보호자)

1. 모든 보호자가 삭제할 수 있다.
2. 처음 피보호자의 안부를 생성한 사람이 소유자가 되어 삭제할 수 있다. => 데이터베이스 수정 필요
3. 모든 보호자는 피보호자의 안부에 내 질문만 삭제할 수 있다. 따라서 피보호자의 안부 데이터 객체를 삭제하기 위해서는 모든 질문들이 삭제되어야 합니다.(모든 보호자가 자신의 질문을 삭제 해야 합니다.) 즉! 피보호자의 안부 지우기 = 해당 안부 중 내 질문 모두 지우기와 기능이 동일 합니다.

**Comment by seungbeom1010** [comment]
=== 6/28 회의 ===
결과 : 3번안 
피보호자의 안부 수정권한은 해당 질문의 소유자에 있다. (보호자는 본인 질문만 수정 가능, 안부 내 질문이 없을 경우 자동삭제)

1번과 2번의 경우, 무질서한 흐름이 예상, 권한남용이 될 우려가 있다.
